import type { ExpenseItem } from "./types";

// Placeholder data for a breakfast restaurant (ร้านอาหารเช้า) standing in for
// the real expense feed — vendors and descriptions are food-service costs
// (fresh market ingredients, gas, packaging, staff wages) rather than
// generic office spend. Dated in April 2026 (the "current" reference month
// used by ExpenseSummaryCards is May 2026) so the monthly card reads 0
// while the yearly card still totals something — same shape as the source
// reference (this month is empty, the year-to-date isn't).
export const MOCK_EXPENSES: ExpenseItem[] = [
  {
    id: "exp-001",
    date: "2026-04-02",
    documentType: "ใบเสร็จรับเงิน",
    vendor: "ตลาดสดเช้าสี่มุมเมือง",
    description: "ค่าวัตถุดิบสด (ผัก เนื้อ ไข่)",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "จ่ายแล้ว",
    amount: 4250,
  },
  {
    id: "exp-002",
    date: "2026-04-03",
    documentType: "สลิปโอนเงิน",
    vendor: "ร้านกาแฟคั่วบ้านๆ",
    description: "ค่าเมล็ดกาแฟและนมสด",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "จ่ายแล้ว",
    amount: 1640,
  },
  {
    id: "exp-003",
    date: "2026-04-08",
    documentType: "ใบเสร็จรับเงิน",
    vendor: "ร้านแก๊สหุงต้มบุญมี",
    description: "ค่าแก๊สหุงต้มถังใหญ่ 2 ถัง",
    payer: "ผู้จัดการร้าน อนัญญา",
    status: "จ่ายแล้ว",
    amount: 1600,
  },
  {
    id: "exp-004",
    date: "2026-04-09",
    documentType: "อื่นๆ",
    vendor: "-",
    description: "ค่าน้ำมันไปตลาด",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "รอจ่าย",
    amount: 310,
  },
  {
    id: "exp-005",
    date: "2026-04-16",
    documentType: "สลิปโอนเงิน",
    vendor: "เจ้าของอาคาร คุณวัฒนวิก",
    description: "ค่าเช่าร้านเดือน เม.ย.",
    payer: "ผู้จัดการร้าน อนัญญา",
    status: "จ่ายแล้ว",
    amount: 15000,
  },
  {
    id: "exp-006",
    date: "2026-04-17",
    documentType: "ใบเสร็จรับเงิน",
    vendor: "บมจ. การไฟฟ้า",
    description: "ค่าไฟฟ้าร้านเดือน เม.ย.",
    payer: "ผู้จัดการร้าน อนัญญา",
    status: "จ่ายแล้ว",
    amount: 3590,
  },
  {
    id: "exp-007",
    date: "2026-04-21",
    documentType: "อื่นๆ",
    vendor: "-",
    description: "ค่าถุงพลาสติกใส่กับข้าว",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "จ่ายแล้ว",
    amount: 210,
  },
  {
    id: "exp-008",
    date: "2026-04-23",
    documentType: "สลิปโอนเงิน",
    vendor: "ตลาดสดเช้าสี่มุมเมือง",
    description: "ค่าวัตถุดิบสด (ปลา หมู ผัก)",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "จ่ายแล้ว",
    amount: 3130,
  },
  {
    id: "exp-009",
    date: "2026-04-24",
    documentType: "ใบกำกับภาษี",
    vendor: "บจก. ครัวเรือนอุปกรณ์",
    description: "ค่ากระทะและอุปกรณ์ครัว",
    payer: "ผู้จัดการร้าน อนัญญา",
    status: "ยกเลิก",
    amount: 8900,
  },
  {
    id: "exp-010",
    date: "2026-04-29",
    documentType: "ใบเสร็จรับเงิน",
    vendor: "ร้านข้าวสารบุญมี",
    description: "ค่าข้าวสารและเส้นก๋วยเตี๋ยว",
    payer: "แม่ครัวใหญ่ สมศรี",
    status: "รอจ่าย",
    amount: 2460.74,
  },
  {
    id: "exp-011",
    date: "2026-04-30",
    documentType: "สลิปโอนเงิน",
    vendor: "ทีมพนักงานเสิร์ฟ",
    description: "ค่าจ้างพนักงานรายวัน",
    payer: "ผู้จัดการร้าน อนัญญา",
    status: "จ่ายแล้ว",
    amount: 10050,
  },
];
