import type { ExpenseItem } from "./types";

// Placeholder data for a breakfast-soup restaurant that photographs each
// customer's order slip and prices it from the photo — rows are customer
// orders, not the restaurant's own expenses. Two full weeks (6–12 and
// 13–19 April 2026), a dozen-ish orders each, so week grouping actually
// reads as "a busy week" instead of two or three lonely rows.
// customerName is only set when the photographed slip actually named the
// customer — table numbers and delivery-platform orders leave it unset,
// which the list renders as "ไม่ทราบชื่อ". uploadedBy cycles through the
// small front-of-house staff roster who actually snap and upload each slip.
export const MOCK_EXPENSES: ExpenseItem[] = [
  // Week of 6–12 Apr
  {
    id: "ord-001",
    date: "2026-04-06",
    customerName: "คุณสมชาย",
    description: "โต๊ะ 2 - ข้าวต้มหมูสับ 2 ที่, ไข่ลวก 1 ฟอง",
    uploadedAt: "06:45",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 90,
  },
  {
    id: "ord-002",
    date: "2026-04-06",
    customerName: "คุณสุภาพร",
    description: "เดลิเวอรี่ #Grab1042 - โจ๊กไก่ฉีก 1, น้ำเปล่า 1",
    uploadedAt: "07:10",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 65,
  },
  {
    id: "ord-003",
    date: "2026-04-07",
    customerName: "คุณธนกร",
    description: "โต๊ะ 5 - ก๋วยจั๊บน้ำข้น หมูกรอบ 1 ที่",
    uploadedAt: "07:30",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 55,
  },
  {
    id: "ord-004",
    date: "2026-04-07",
    customerName: "คุณสมชาย",
    description: "ข้าวต้มปลากะพง 1 ที่",
    uploadedAt: "08:05",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 75,
  },
  {
    id: "ord-005",
    date: "2026-04-08",
    customerName: "คุณมานี",
    description: "โต๊ะ 1 - โจ๊กหมูใส่ไข่, ไข่ต้ม 1 ฟอง",
    uploadedAt: "06:55",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 60,
  },
  {
    id: "ord-006",
    date: "2026-04-08",
    customerName: "คุณกิตติ",
    description: "เดลิเวอรี่ #LINEMAN0098 - ปาท่องโก๋ 4 ชิ้น, น้ำเต้าหู้ 1",
    uploadedAt: "07:40",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 45,
  },
  {
    id: "ord-007",
    date: "2026-04-08",
    customerName: "คุณพิมพ์ชนก",
    description: "โต๊ะ 6 - ก๋วยจั๊บรวม หมู+เครื่องใน 1 ที่",
    uploadedAt: "08:20",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 65,
  },
  {
    id: "ord-008",
    date: "2026-04-09",
    description: "โต๊ะ 3 - ข้าวต้มไก่ 2 ที่, ไข่เจียว 1",
    uploadedAt: "07:00",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 130,
  },
  {
    id: "ord-009",
    date: "2026-04-09",
    customerName: "คุณมานี",
    description: "โจ๊กไข่เยี่ยวม้า พิเศษ 1 ที่",
    uploadedAt: "07:50",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 70,
  },
  {
    id: "ord-010",
    date: "2026-04-10",
    customerName: "คุณณัฐวุฒิ",
    description: "เดลิเวอรี่ #Grab1187 - กาแฟเย็น 2, ขนมปังปิ้ง 1",
    uploadedAt: "08:10",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 95,
  },
  {
    id: "ord-011",
    date: "2026-04-11",
    customerName: "คุณศิริพร",
    description: "โต๊ะ 4 - ก๋วยจั๊บน้ำใส หมู 1 ที่",
    uploadedAt: "06:50",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 50,
  },
  {
    id: "ord-012",
    date: "2026-04-12",
    customerName: "คุณวราภรณ์",
    description: "โต๊ะ 8 - ข้าวต้มทะเล 1, ก๋วยจั๊บ 1 ที่",
    uploadedAt: "09:15",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 110,
  },

  // Week of 13–19 Apr
  {
    id: "ord-013",
    date: "2026-04-13",
    customerName: "คุณอนุชา",
    description: "โต๊ะ 2 - โจ๊กหมู 2 ที่",
    uploadedAt: "06:40",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 120,
  },
  {
    id: "ord-014",
    date: "2026-04-13",
    customerName: "คุณสุภาวดี",
    description: "เดลิเวอรี่ #Grab1233 - ข้าวต้มหมูสับ 1, น้ำเปล่า 1",
    uploadedAt: "07:25",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 70,
  },
  {
    id: "ord-015",
    date: "2026-04-14",
    customerName: "คุณชาญชัย",
    description: "โต๊ะ 7 - ก๋วยจั๊บใส่ไข่ 1 ที่",
    uploadedAt: "07:55",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 60,
  },
  {
    id: "ord-016",
    date: "2026-04-14",
    customerName: "คุณวิภา",
    description: "ชุดเช้า - กาแฟร้อน 1, ปาท่องโก๋ 3",
    uploadedAt: "08:30",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 55,
  },
  {
    id: "ord-017",
    date: "2026-04-15",
    customerName: "คุณเอกชัย",
    description: "โต๊ะ 1 - ข้าวต้มรวมทะเล 1 ที่",
    uploadedAt: "07:05",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 100,
  },
  {
    id: "ord-018",
    date: "2026-04-15",
    customerName: "คุณรัตนา",
    description: "โต๊ะ 3 - โจ๊กหมู, ไข่ลวก 1",
    uploadedAt: "07:35",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 65,
  },
  {
    id: "ord-019",
    date: "2026-04-16",
    customerName: "คุณปรีชา",
    description: "เดลิเวอรี่ #LINEMAN0155 - ก๋วยจั๊บหมูกรอบ 2 ที่",
    uploadedAt: "06:45",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 110,
  },
  {
    id: "ord-020",
    date: "2026-04-16",
    customerName: "คุณกมลวรรณ",
    description: "โต๊ะ 5 - ข้าวต้มไก่ 1 ที่",
    uploadedAt: "08:00",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 65,
  },
  {
    id: "ord-021",
    date: "2026-04-17",
    customerName: "คุณอนันต์",
    description: "โจ๊กพิเศษ 2 ที่",
    uploadedAt: "07:15",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 140,
  },
  {
    id: "ord-022",
    date: "2026-04-18",
    customerName: "คุณจิราพร",
    description: "โต๊ะ 9 - ชุดเครื่องดื่ม น้ำเต้าหู้ 2, ปาท่องโก๋ 2",
    uploadedAt: "08:45",
    uploadedBy: "แม่ครัวใหญ่ สมศรี",
    amount: 60,
  },
  {
    id: "ord-023",
    date: "2026-04-19",
    customerName: "คุณธีรภัทร",
    description: "โต๊ะ 2 - ก๋วยจั๊บ 1, โจ๊ก 1 ที่",
    uploadedAt: "07:20",
    uploadedBy: "พนักงานเสิร์ฟ นภา",
    amount: 120,
  },
  {
    id: "ord-024",
    date: "2026-04-19",
    customerName: "คุณนฤมล",
    description: "เดลิเวอรี่ #Grab1301 - ข้าวต้มปลา 1 ที่",
    uploadedAt: "09:05",
    uploadedBy: "ผู้จัดการร้าน อนัญญา",
    amount: 75,
  },
];
