export type FoodType = "ข้าวต้ม" | "โจ๊ก" | "ก๋วยจั๊บ" | "อื่นๆ";

export const ORDER_TYPE_VALUES = ["dine_in", "takeaway", "delivery", "unknown"] as const;
export type OrderType = (typeof ORDER_TYPE_VALUES)[number];

export const ORDER_TYPE_LABELS: Record<OrderType, string> = {
  dine_in: "ทานที่ร้าน",
  takeaway: "รับกลับ",
  delivery: "เดลิเวอรี่",
  unknown: "ไม่ระบุ",
};

export interface OrderLineItem {
  menuItemId: string;
  quantity: number;
}

export interface OrderTopping {
  id: string;
  name: string;
  quantity: number;
  unit: string;
  unitPrice: number | null;
  totalPrice: number | null;
  confidence: number;
  needsReview: boolean;
  humanReviewed: boolean;
  /** Text seen by OCR before reconciliation with the configured options. */
  rawText?: string;
}

export interface OrderItem {
  lineId: string;
  menuItemId: string | null;
  menuItemName: string;
  quantity: number;
  unit: string;
  toppings: OrderTopping[];
  unitPrice: number | null;
  totalPrice: number | null;
  notes: string;
  confidence: number;
  needsReview: boolean;
  humanReviewed: boolean;
  /** OCR evidence is retained; billing always uses the configured menu price. */
  rawText?: string;
  ocrUnitPrice?: number | null;
  ocrTotalPrice?: number | null;
}

export interface OrderToppingDraft extends Omit<OrderTopping, "unitPrice" | "totalPrice"> {
  unitPrice: number | "";
  totalPrice: number | "";
}

export interface OrderItemDraft extends Omit<OrderItem, "toppings" | "unitPrice" | "totalPrice"> {
  toppings: OrderToppingDraft[];
  unitPrice: number | "";
  totalPrice: number | "";
}

/** The normalized fields returned by the order OCR endpoint. */
export interface OrderOcrFields {
  /** Always set: read from the image or generated by the server when absent. */
  orderNumber: string;
  orderNumberSource: "image" | "generated";
  customerName: string | null;
  orderedAt: string | null;
  orderedAtSource: "image" | "file_metadata" | "missing";
  orderType: OrderType;
  items: OrderItem[];
  notes: string | null;
  subtotal: number | null;
  tax: number | null;
  discount: number | null;
  totalAmount: number | null;
  confidence: number;
  needsReview: boolean;
  reviewReasons: string[];
  rawText: string;
}

/** Local editable shape used by the upload panel. */
export interface OrderDraft {
  orderNumber: string;
  customerName: string;
  orderedAt: string;
  orderType: OrderType;
  items: OrderItemDraft[];
  notes: string;
  totalAmount: number | "";
  confidence: number;
  needsReview: boolean;
  reviewReasons: string[];
  humanReviewed: boolean;
  rawText: string;
}

export interface ExpenseItem {
  id: string;
  /** Unique order number read from the order slip. */
  orderNumber: string;
  /** ISO date derived from orderedAt, e.g. "2026-04-16". */
  date: string;
  /** ISO local datetime, e.g. "2026-04-16T07:42:00". */
  orderedAt: string;
  orderType: OrderType;
  customerName?: string;
  items: OrderItem[];
  notes: string;
  /** Kept for the menu sales aggregation contract. */
  lineItems?: OrderLineItem[];
  /** Backward-compatible compact display text for existing list consumers. */
  description: string;
  /** Time the order photo was uploaded, e.g. "07:42". */
  uploadedAt: string;
  uploadedBy: string;
  /** In-session object URL for the uploaded order slip prototype. */
  imageUrl?: string;
  confidence?: number;
  humanReviewed?: boolean;
  amount: number;
}
